export const defaultTaskRoutines = [
  {
    title: "Dish duty",
    description: "Shared cooking and tea dishes only. Everyone still washes their own personal dishes.",
    area: "Kitchen",
    difficulty: "easy",
    difficulty_reason: "Short shared reset after meals or tea.",
    estimated_minutes: 12,
    points: 3,
    points_reason: "A small, frequent shared responsibility.",
    frequency: "daily",
    checklist: ["Wash shared dishes", "Clean tea kettle and shared utensils", "Reset sink area"],
    proof_required: false,
    dueOffset: 0,
  },
  {
    title: "Kitchen reset",
    description: "Return the shared kitchen to a ready-to-use state after communal cooking.",
    area: "Kitchen",
    difficulty: "medium",
    difficulty_reason: "Several surfaces and waste checks are involved.",
    estimated_minutes: 20,
    points: 6,
    points_reason: "More steps and more shared benefit than a quick task.",
    frequency: "daily",
    checklist: ["Wash shared cooking dishes", "Clean sink", "Wipe counters", "Clean stove", "Empty food waste"],
    proof_required: false,
    dueOffset: 0,
  },
  {
    title: "Food waste bin",
    description: "Empty food waste before it smells and replace the liner.",
    area: "Kitchen",
    difficulty: "easy",
    difficulty_reason: "Quick but time-sensitive hygiene task.",
    estimated_minutes: 7,
    points: 2,
    points_reason: "Short hygiene task with low physical effort.",
    frequency: "every_second_day",
    checklist: ["Tie food waste bag", "Move it to the correct outside bin", "Fit a new liner"],
    proof_required: false,
    dueOffset: 1,
  },
  {
    title: "Bathroom clean",
    description: "Complete the full shared bathroom routine.",
    area: "Shared bathroom",
    difficulty: "heavy",
    difficulty_reason: "A full hygiene clean with multiple fixtures and floor work.",
    estimated_minutes: 40,
    points: 8,
    points_reason: "Heavy task requiring time, care, and before/after proof.",
    frequency: "weekly",
    checklist: ["Toilet cleaned", "Sink cleaned", "Mirror cleaned", "Floor cleaned", "Toilet paper checked"],
    proof_required: true,
    dueOffset: 3,
  },
  {
    title: "Vacuum and mop",
    description: "Vacuum and mop the main shared floor areas.",
    area: "Shared areas",
    difficulty: "heavy",
    difficulty_reason: "Large-area physical task with equipment setup and cleanup.",
    estimated_minutes: 45,
    points: 8,
    points_reason: "High effort and broad benefit to the household.",
    frequency: "weekly",
    checklist: ["Clear floor obstacles", "Vacuum shared floors", "Mop hard floors", "Return cleaning tools"],
    proof_required: true,
    dueOffset: 5,
  },
  {
    title: "Bins outside",
    description: "Put the correct collection bins outside on collection evening.",
    area: "Outside bins",
    difficulty: "medium",
    difficulty_reason: "Time-sensitive and may involve heavy bins.",
    estimated_minutes: 10,
    points: 5,
    points_reason: "Missing it affects the whole house for another week.",
    frequency: "weekly",
    checklist: ["Check collection schedule", "Move correct bins outside", "Secure lids"],
    proof_required: false,
    dueOffset: 4,
  },
] as const;

export const defaultGroceries = [
  ["Milk", "Dairy"],
  ["Bread", "Bakery"],
  ["Eggs", "Dairy"],
  ["Onions", "Produce"],
  ["Tomatoes", "Produce"],
  ["Chicken", "Meat"],
  ["Dishwashing liquid", "Cleaning"],
  ["Bin bags", "Household"],
  ["Tissue rolls", "Household"],
] as const;

export function addDaysIso(offset: number) {
  const date = new Date();
  date.setHours(12, 0, 0, 0);
  date.setDate(date.getDate() + offset);
  return date.toISOString().slice(0, 10);
}

